### PR TITLE
Timeout member added to ehrclient class

### PR DESCRIPTION
**Pull request by Vortex-21**
## Description

Timeout member added as requested. 

## Related Issue

https://github.com/dotimplement/HealthChain/issues/67

## Changes Made

-added timeout as a member in the ehrclient 
-passed timeout as config in the related TODO
-

## Testing

Tested against the already existing tests . 

## Checklist

- [x] I have read the [contributing](https://github.com/dotimplement/HealthChain/CONTRIBUTING.md) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Vortex-21** [comment]
I have made the necessary changes as requested . Hope it works fine!

**Review by jenniferjiangkells — CHANGES_REQUESTED** [review]
Exactly what we want ⭐ Could you just update the docstring to reflect the new parameter? Thanks!

**Comment by Vortex-21** [comment]
I have updated the docstring !

**Review by adamkells — APPROVED** [review]
LGTM!

**Review by jenniferjiangkells — APPROVED** [review]

**Pull request merged**
